services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    command: >
      bash -c "
        echo 'KafkaServer {
          org.apache.kafka.common.security.plain.PlainLoginModule required
          username=\"admin\"
          password=\"admin-secret\"
          user_admin=\"admin-secret\";
        };' > /tmp/kafka_server_jaas.conf &&
        export KAFKA_OPTS='-Djava.security.auth.login.config=/tmp/kafka_server_jaas.conf' &&
        /etc/confluent/docker/run
      "
    environment:
      CLUSTER_ID: '5L6g3nShT-eMCtK--X86sw'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'SASL_PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://localhost:9092'
      KAFKA_ADVERTISED_LISTENERS: 'SASL_PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'SASL_PLAINTEXT'
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  db-service:
    build:
      context: .
      dockerfile: db-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      PORT: 8083

  store-service:
    build:
      context: .
      dockerfile: store-service/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
      PORT: 8080
      DB_MODE: "memory"
      SASL_USER: admin
      SASL_PASSWORD: admin-secret
      SASL_MECHANISM: PLAIN
      SASL_ENABLE: "true"
    ports:
      - "8080:8080"

  operator-service:
    build:
      context: .
      dockerfile: operator-service/Dockerfile
    depends_on:
      - kafka
      - db-service
    environment:
      KAFKA_BROKERS: kafka:29092
      PORT: 8082
      DB_URL: "http://db-service:8083"
      SASL_USER: admin
      SASL_PASSWORD: admin-secret
      SASL_MECHANISM: PLAIN
      SASL_ENABLE: "true"

  backend-service:
    build:
      context: .
      dockerfile: backend-service/Dockerfile
    depends_on:
      - kafka
      - db-service
    ports:
      - "8081:8081"
    environment:
      KAFKA_BROKERS: kafka:29092
      PORT: 8081
      DB_URL: "http://db-service:8083"
      SASL_USER: admin
      SASL_PASSWORD: admin-secret
      SASL_MECHANISM: PLAIN
      SASL_ENABLE: "true"